name: Check Public APIs

on:
  # Triggers the workflow on push events
  push:
  # Triggers the workflow on pull request events
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  update-apis:
    runs-on: ubuntu-latest
    name: Update Public API goldens
    steps:
      - uses: actions/setup-node@v3
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            npm-node-
      - name: Install Deps
        run: npm ci --ignore-scripts
      - name: Build
        run: npm run build
      - name: Commit Public API
        run: .github/workflows/commit-api.sh
